import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";
import Header from "~/components/Header/Header";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen dark:bg-[#121212] px-2 py-2">
        <Header/>
        <div className="h-screen dark:bg-[#121212]">
          <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl p-4 dark:text-white dark:hover:bg-gray-600"
              href="/test404"
            >
              <h3 className="text-2xl font-bold">404 Page →</h3>
              <div className="text-lg">
                404 TEST LINK
              </div>
          </Link>
        </div>
      </main>
    </>
  );
};

export default Home;